version: '3'

services:
  jupyterhub:
    image: jupyterhub
    build: ./jupyterhub
    container_name: jupyterhub-hub
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8888:8000
    environment:
      DOCKER_JUPYTER_IMAGE: jupyter/scipy-notebook
      DOCKER_NETWORK_NAME: jupyterhub_default
      HUB_IP: jupyterhub-hub
      VIRTUAL_HOST: jupyterhub.biohse.ru
      LETSENCRYPT_HOST: jupyterhub.biohse.ru
      VIRTUAL_PORT: 8888
