name: 'Setup Ansible'
description: 'Setting up Ansible config, Vault key, etc'
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible requests
    - name: Setup Ansible
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir .ssh
        echo "$SSH_KEY" > .ssh/ansible.key
        chmod 600 .ssh/ansible.key
        cd ansible
        echo "$ANSIBLE_VAULT_PASSWORD" > .vault_password
        mv ansible-ci.cfg ansible.cfg
        ansible-galaxy install -r requirements.yml