version: "3.2"
services:
  outline:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    volumes:
      - uptime-kuma:/app/data
    environment:
      VIRTUAL_HOST: uptime.biohse.ru
      LETSENCRYPT_HOST: uptime.biohse.ru
      VIRTUAL_PORT: 3000

volumes:
  uptime-kuma:
