---
  - name: Deploy Galaxy
    hosts: "{{ target_hosts | default('junior') }}"
    vars:
      app_name: galaxy
    tasks:
      - name: Creates directory
        file:
          path: .ansible/{{ app_name }}/{{ item }}
          state: directory
        loop:
          - /
          - /build/

      - name: Template files
        template:
          src: "{{ app_name }}/{{ item }}.j2"
          dest: .ansible/{{ app_name }}/{{ item }}
          mode: 444
        loop:
          - compose.yaml
          - oidc_config.xml
          - oidc_backends_config.xml
          - welcome.html
          - build/Dockerfile
          - build/my_tool_list.yml

      - name: Build
        community.docker.docker_image:
          name: "biohse_{{ app_name }}:latest"
          build:
            nocache: true
            path: .ansible/{{ app_name }}/build/
          debug: true
          source: build
          force_source: true

      - name: Deploy
        environment:
          PATH: /home/ansible/.local/bin:{{ ansible_env.PATH }}
        community.docker.docker_compose_v2:
          project_name: "{{ app_name }}"
          project_src: ".ansible/{{ app_name }}"
          recreate: always
