---
  - name: Deploy Keycloak
    hosts: "{{ target_hosts | default('junior') }}"
    vars_files:
      - ../../manifests/keycloak/secret-env.yaml  
    tasks:
      - name: Install dependencies
        ansible.builtin.pip: 
          name: ["docker", "PyYAML", "docker-compose"]
      - name: Copy Docker Compose files
        copy:
          src: ../../manifests/keycloak # We are in junior_infra/ansible/playbooks
          dest: ".ansible/"
          mode: "0600"
          decrypt: false
      - name: Deploy
        environment:
          PATH: /home/ansible/.local/bin:{{ ansible_env.PATH }}
          KEYCLOAK_ADMIN_PASSWORD: "{{ KEYCLOAK_ADMIN_PASSWORD }}"
          POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
        community.docker.docker_compose_v2:
          project_name: keycloak
          project_src: ".ansible/keycloak"
