---
  - name: Deploy JupyterHub
    hosts: "{{ target_hosts | default('all') }}"
    tasks:
      - name: Deploy
        community.docker.docker_compose:
          project_src: "../jupyterhub"
          files: ["compose.yaml"]
      - name: Show results
        ansible.builtin.debug:
          var: output
