---
  - name: Deploy JupyterHub
    hosts: "{{ target_hosts | default('junior') }}"
    vars_files:
      - ../../manifests/jupyterhub/secret-env.yaml  
    tasks:
      - name: Install dependencies
        ansible.builtin.pip: 
          name: ["docker", "PyYAML", "docker-compose"]
      - name: Copy Docker Compose files
        copy:
          src: ../../manifests/jupyterhub # We are in junior_infra/ansible/playbooks
          dest: ".ansible/"
          mode: "600"
          decrypt: false
      - name: Build Notebook images
        environment:
          PATH: /home/ansible/.local/bin:{{ ansible_env.PATH }}
          DOCKER_BUILDKIT: '1'
        ansible.builtin.shell:
          cmd: |-
            docker compose build 
          chdir: .ansible/jupyterhub/singleuser
      - name: Deploy Hub
        environment:
          PATH: /home/ansible/.local/bin:{{ ansible_env.PATH }}
          OAUTH_CLIENT_SECRET: "{{ OAUTH_CLIENT_SECRET }}"
        community.docker.docker_compose:
          project_src: ".ansible/jupyterhub"
          debug: true
