---
  - name: Deploy Nginx Proxy
    hosts: "{{ target_hosts | default('junior') }}"
    tasks:
      - name: Install dependencies
        ansible.builtin.pip: 
          name: ["docker", "PyYAML", "docker-compose"]
      - name: Copy Docker Compose files
        copy:
          src: ../../manifests/nginx # We are in junior_infra/ansible/playbooks
          dest: ".ansible/"
      - name: Deploy
        environment:
          PATH: /home/ansible/.local/bin:{{ ansible_env.PATH }}
        community.docker.docker_compose_v2:
          project_name: nginx-proxy
          project_src: ".ansible/nginx"
          recreate: always
