---
  - name: Connect to hosts
    hosts: "{{ target_hosts | default('all') }}"
    tasks:
      - name: test connection
        ansible.builtin.ping:
      - name: Privilege escalation
        become: true
        command: ls /root
