version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      com.github.nginx-proxy.nginx: ""
    # environment:
    #   DEFAULT_HOST: jupyterhub.biohse.ru
    networks:
      - jupyterhub_default
      - portainer_bridge
    restart: unless-stopped

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: nkengibaryan@edu.hse.ru
    networks:
      - jupyterhub_default
      - portainer_bridge
    restart: unless-stopped

networks:
  jupyterhub_default:
    external: true
  portainer_bridge:
    external: true

volumes:
  certs: {}
  vhost: {}
  html: {}
  acme: {}