services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    labels:
      com.github.nginx-proxy.nginx: ""
    # environment:
    #   DEFAULT_HOST: jupyterhub.biohse.ru
    networks:
      - jupyterhub_default
      - portainer_bridge
      - cvat_cvat
      - keycloak_default
      - outline_default
      - galaxy_default
      - beszel_hub_default
      - backrest_default
    restart: unless-stopped

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: nkengibaryan@edu.hse.ru
    networks:
      - jupyterhub_default
      - portainer_bridge
      - cvat_cvat
      - keycloak_default
      - outline_default
      - galaxy_default
      - beszel_hub_default
      - backrest_default
    restart: unless-stopped

networks:
  jupyterhub_default:
    external: true
  portainer_bridge:
    external: true
  cvat_cvat:
    external: true
  keycloak_default:
    external: true
  outline_default:
    external: true
  galaxy_default:
    external: true
  beszel_hub_default:
    external: true
  backrest_default:
    external: true

volumes:
  certs: {}
  vhost: {}
  html: {}
  acme: {}
