name: Ansible deploy

on: [push]

jobs:
  jupyterhub:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ansible
      uses: .github/actions/setup-ansible
    - name: Deploy JupyterHub
      env:
        ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
      run: |
        cd ansible
        ansible-playbook playbooks/deploy_jupyter.yaml -e "ansible_user=ansible" -e "ansible_private_key_file=../.ssh/ansible.key" -e "ansible_become_password=$ANSIBLE_USER_PASSWORD" -e "ansible_remote_tmp=/tmp/ansible"

  nginx:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ansible
      uses: .github/actions/setup-ansible
    - name: Deploy Nginx Proxy
      env:
        ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
      run: |
        cd ansible
        ansible-playbook playbooks/deploy_proxy.yaml -e "ansible_user=ansible" -e "ansible_private_key_file=../.ssh/ansible.key" -e "ansible_become_password=$ANSIBLE_USER_PASSWORD" -e "ansible_remote_tmp=/tmp/ansible"

  keycloak:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ansible
      uses: .github/actions/setup-ansible
    - name: Deploy Keycloak
      env:
        ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
      run: |
        cd ansible
        ansible-playbook playbooks/deploy_keycloak.yaml -e "ansible_user=ansible" -e "ansible_private_key_file=../.ssh/ansible.key" -e "ansible_become_password=$ANSIBLE_USER_PASSWORD" -e "ansible_remote_tmp=/tmp/ansible"

  outline:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ansible
      uses: .github/actions/setup-ansible
    - name: Deploy Outline Wiki
      env:
        ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
      run: |
        cd ansible
        ansible-playbook playbooks/deploy_outline.yaml -e "ansible_user=ansible" -e "ansible_private_key_file=../.ssh/ansible.key" -e "ansible_become_password=$ANSIBLE_USER_PASSWORD" -e "ansible_remote_tmp=/tmp/ansible"
