name: Ansible deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible requests
    - name: Setup Ansible
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir .ssh
        echo "$SSH_KEY" > .ssh/ansible.key
        chmod 600 .ssh/ansible.key
        cd ansible
        echo "$ANSIBLE_VAULT_PASSWORD" > .vault_password
        mv ansible-ci.cfg ansible.cfg
        ansible-galaxy install -r requirements.yml

    - name: Deploy JupyterHub
      env:
        ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
      run: |
        cd ansible
        ansible-playbook playbooks/deploy_jupyter.yaml -e "ansible_user=ansible" -e "ansible_private_key_file=../.ssh/ansible.key" -e "ansible_become_password=$ANSIBLE_USER_PASSWORD" -e "ansible_remote_tmp=/tmp/ansible"

    - name: Deploy Nginx Proxy
      env:
        ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
      run: |
        cd ansible
        ansible-playbook playbooks/deploy_proxy.yaml -e "ansible_user=ansible" -e "ansible_private_key_file=../.ssh/ansible.key" -e "ansible_become_password=$ANSIBLE_USER_PASSWORD" -e "ansible_remote_tmp=/tmp/ansible"

    - name: Deploy Keycloak
      env:
        ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
      run: |
        cd ansible
        ansible-playbook playbooks/deploy_keycloak.yaml -e "ansible_user=ansible" -e "ansible_private_key_file=../.ssh/ansible.key" -e "ansible_become_password=$ANSIBLE_USER_PASSWORD" -e "ansible_remote_tmp=/tmp/ansible"

    - name: Deploy Keycloak
      env:
        ANSIBLE_USER_PASSWORD: ${{ secrets.ANSIBLE_USER_PASSWORD }}
      run: |
        cd ansible
        ansible-playbook playbooks/deploy_outline.yaml -e "ansible_user=ansible" -e "ansible_private_key_file=../.ssh/ansible.key" -e "ansible_become_password=$ANSIBLE_USER_PASSWORD" -e "ansible_remote_tmp=/tmp/ansible"